### ISSUE TITLE
About https://nunie123.github.io/sqlalchemy-validation.html

### ISSUE THREAD

**Issue by cleberangelo** [Nunie123/narratus#10]
Sorry about that, i need to talk with yout about this post and i did not found a contact. There are some issue in your sample, the messages in "raise AssertionError" from models are not going back to the view, they are going to the python console. I think that the point in routes where the messagem came from the model validator is
try: ... except AssertionError as exception_message:
but, the ajax call return an internal server error instead of the error messages.
I'm a Java developer trying to learn python and Flask, so, if you could give me some tip about.
The code from your post I have grouped in a single file, here are the codes plus a html page with an ajax call (https://gist.github.com/cleberangelo/264d29b9c4f4d335a0c2f35dfca2ab78)
Thanks.

**Comment by Nunie123** [comment]
Hello @cleberangelo.

If I were to guess from looking at your code, I'd say the issue is in lines 80 and 81.  My guess is the assertion error is happening when those lines execute, and since they are not in a try block it's going right to console.

Let me know if that doesn't fix it and I'll take another look.

**Comment by cleberangelo** [comment]
That's right. I moved the 
```
    user = User(username=username, email=email)
    user.set_password(password)
```
inside the try block, using curl
```
    curl -i -X POST -H 'Content-Type: application/json' -d '{"username": "Other item", "password": "PassWord", "email": "user@password"}' http://127.0.0.1:5000/create
```
I get 
```
 HTTP/1.0 400 BAD REQUEST
Content-Type: application/json
Content-Length: 63
Server: Werkzeug/0.14.1 Python/3.6.5
Date: Mon, 09 Jul 2018 17:13:52 GMT

{
  "msg": "Error: Provided email is not an email address. "
}
```
Do you know if @validates from SqlAlchemy can be used for html forms too?

Thanks for your help!

**Comment by Nunie123** [comment]
I think this should work for form data, as the input is handled in the route, separate from the validation happening in the model layer.

**Comment by cleberangelo** [comment]
Yes, it works. Instead of jsonify, flash
````
try:
    user = User(username=username, email=email)
    user.set_password(password)

    db.session.add(user)
    db.session.commit()
    flash('Saved with id {}'.format(user.id), 'success')
    return redirect(url_for('home'))
  except AssertionError as exception_message:
    flash('{}'.format(exception_message), 'danger')
    return redirect(url_for('home'))
